name: ci
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *' # Every four hours

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
    - run: npx -y -p sill-api@latest build-data
      env:
        DATA_REPO_SSH_URL: ${{github.event.repository.ssh_url}}
        SSH_PRIVATE_KEY_NAME: ${{secrets.SSH_PRIVATE_KEY_NAME}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        INCREMENTAL: ${{github.event_name == 'push'}}
        
        
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
